services:
  page-one_mongodb:
    container_name: backend_mongodb
    image: 'bitnami/mongodb:latest'
    ports:
      - '27017:27017'
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      retries: 5
      timeout: 5s
  backend_insert_data:
    container_name: backend_insert_data
    image: 'iragca/page-one-insert_data:latest'
    depends_on:
      page-one_mongodb:
        condition: service_healthy
    command: [ "sh", "-c", "python insert_data.py" ]
  backend_webapp:
    container_name: backend_webapp
    image: 'iragca/page-one-backend:latest'
    depends_on:
      page-one_mongodb:
        condition: service_healthy
    ports:
      - '5000:5000'
    environment:
      MONGO_URI: mongodb://backend_mongodb:27017/pageone?serverSelectionTimeoutMS=2000
